# Generated by Django 3.1.7 on 2021-06-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.IntegerField()),
                ('content', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='BackUpHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=50)),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.backupobject')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where', to='db.backupobject')),
            ],
        ),
    ]
