# Generated by Django 3.1.7 on 2021-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20210628_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('gid', models.CharField(max_length=250)),
                ('ver', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BackUpHandler',
        ),
    ]
